<?php
/**
 * @file
 * Code that overrides the DDBCMS feautures.
 */

/**
 * Implements hook_field_default_field_instances_alter().
 */
function bibsdb_features_override_field_default_field_instances_alter(&$data) {


  // Change the image style of the news list image in search results
  if (isset($data['node-ding_news-field_ding_news_list_image'])) {
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['breakpoint_1'] = 768; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['breakpoint_2'] = 500; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['fallback_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['max_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['style_1'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['style_2'] = 'bibsdb_list_large'; /* WAS: '' */
  }

  // Change the image style of the event list image in search results
  if (isset($data['node-ding_event-field_ding_event_list_image'])) {
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['image_link'] = 'content'; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['breakpoint_1'] = 768; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['breakpoint_2'] = 500; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['fallback_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['max_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['style_1'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['style_2'] = 'bibsdb_list_large'; /* WAS: '' */
  }

  
  // Change the image style of the news title image in node view
  if (isset($data['node-ding_news-field_ding_news_title_image'])) {
    $data['node-ding_news-field_ding_news_title_image']['display']['default']['settings']['styles']['fallback_style'] = 'bibsdb_expose_large'; /* WAS: 'ding_panorama_primary_large' */
    $data['node-ding_news-field_ding_news_title_image']['display']['default']['settings']['styles']['max_style'] = 'bibsdb_expose_large'; /* WAS: 'ding_panorama_primary_large' */
    $data['node-ding_news-field_ding_news_title_image']['display']['default']['settings']['styles']['style_1'] = 'ding_primary_small'; /* WAS: 'ding_panorama_primary_medium' */
    $data['node-ding_news-field_ding_news_title_image']['display']['default']['settings']['styles']['style_2'] = 'ding_primary_small'; /* WAS: 'ding_panorama_primary_small' */
  }
}


function bibsdb_features_override_strongarm_alter(&$data) {

  // Make news content unpublished as default
  if (isset($data['node_options_ding_news'])) {
    unset($data['node_options_ding_news']->value[0]);
  }

  // Make event content unpublished and promoted as default
  if (isset($data['node_options_ding_event'])) {
    $data['node_options_ding_event']->value[0] = 'promote'; /* WAS: 'status' */
  }
}


function bibsdb_features_override_default_page_manager_pages_alter(&$data) {
  if (isset($data['ding_events'])) {
    $data['ding_events']->default_handlers['page_ding_events_panel_context']->conf['display']->content['new-5d683c57-a79e-4d16-9046-d2dc04a557d5']->position = 3; /* WAS: 2 */
    $data['ding_events']->default_handlers['page_ding_events_panel_context']->conf['display']->content['new-fc70425c-d883-42de-87da-ccf4782400e3'] = (object) array(
          'pid' => 'new-fc70425c-d883-42de-87da-ccf4782400e3',
          'panel' => 'main_content',
          'type' => 'views_panes',
          'subtype' => 'bibsdb_wall-panel_bibsdb_wall',
          'shown' => TRUE,
          'access' => array(),
          'configuration' => array(
            'arguments' => array(
              'field_bibsdb_wall_tid' => 176,
            ),
          ),
          'cache' => array(),
          'style' => array(
            'settings' => NULL,
          ),
          'css' => array(),
          'extras' => array(),
          'position' => 2,
          'locks' => array(),
          'uuid' => 'fc70425c-d883-42de-87da-ccf4782400e3',
        ); /* WAS: '' */
    $data['ding_events']->default_handlers['page_ding_events_panel_context']->conf['display']->panels['main_content'][2] = 'new-fc70425c-d883-42de-87da-ccf4782400e3'; /* WAS: 'new-5d683c57-a79e-4d16-9046-d2dc04a557d5' */
    $data['ding_events']->default_handlers['page_ding_events_panel_context']->conf['display']->panels['main_content'][3] = 'new-5d683c57-a79e-4d16-9046-d2dc04a557d5'; /* WAS: '' */
  }
}

