<?php
/**
 * @file
 * Code that overrides the DDBCMS feautures.
 */


/**
 * Implements hook_ctools_plugin_api().
 */
function pathautotest_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_field_default_field_bases_alter().
 */
function bibsdb_features_override_field_default_field_bases_alter(&$data) {
  if (isset($data['field_ding_event_category'])) {
    $data['field_ding_event_category']['cardinality'] = 5; /* WAS: 1 */
  }
  if (isset($data['field_ting_new_materials_search'])) {
    $data['field_ting_new_materials_search']['type'] = 'text_long'; /* WAS: 'text' */
    unset($data['field_ting_new_materials_search']['settings']['max_length']);
  }
}

/**
 * Implements hook_field_default_field_instances_alter().
 */
function bibsdb_features_override_field_default_field_instances_alter(&$data) {


  // Change the image style of the news list image in search results
  if (isset($data['node-ding_news-field_ding_news_list_image'])) {
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['breakpoint_1'] = 768; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['breakpoint_2'] = 500; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['fallback_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['max_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['style_1'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_news-field_ding_news_list_image']['display']['search_result']['settings']['styles']['style_2'] = 'bibsdb_list_large'; /* WAS: '' */
  }

  // Change the image style of the event list image in search results
  if (isset($data['node-ding_event-field_ding_event_list_image'])) {
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['image_link'] = 'content'; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['breakpoint_1'] = 768; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['breakpoint_2'] = 500; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['fallback_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['max_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['style_1'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_event-field_ding_event_list_image']['display']['search_result']['settings']['styles']['style_2'] = 'bibsdb_list_large'; /* WAS: '' */
  }

  // Change the image style of the page list image in search results
  if (isset($data['node-ding_page-field_ding_page_list_image'])) {
    $data['node-ding_page-field_ding_page_list_image']['display']['search_result']['settings']['image_link'] = 'content'; /* WAS: '' */
    $data['node-ding_page-field_ding_page_list_image']['display']['search_result']['settings']['styles']['breakpoint_1'] = 768; /* WAS: '' */
    $data['node-ding_page-field_ding_page_list_image']['display']['search_result']['settings']['styles']['breakpoint_2'] = 500; /* WAS: '' */
    $data['node-ding_page-field_ding_page_list_image']['display']['search_result']['settings']['styles']['fallback_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_page-field_ding_page_list_image']['display']['search_result']['settings']['styles']['max_style'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_page-field_ding_page_list_image']['display']['search_result']['settings']['styles']['style_1'] = 'bibsdb_list_large'; /* WAS: '' */
    $data['node-ding_page-field_ding_page_list_image']['display']['search_result']['settings']['styles']['style_2'] = 'bibsdb_list_large'; /* WAS: '' */
  }

  
  // Change the image style of the news title image in node view
  if (isset($data['node-ding_news-field_ding_news_title_image'])) {
    $data['node-ding_news-field_ding_news_title_image']['display']['default']['settings']['styles']['fallback_style'] = 'bibsdb_expose_large'; /* WAS: 'ding_panorama_primary_large' */
    $data['node-ding_news-field_ding_news_title_image']['display']['default']['settings']['styles']['max_style'] = 'bibsdb_expose_large'; /* WAS: 'ding_panorama_primary_large' */
    $data['node-ding_news-field_ding_news_title_image']['display']['default']['settings']['styles']['style_1'] = 'ding_primary_small'; /* WAS: 'ding_panorama_primary_medium' */
    $data['node-ding_news-field_ding_news_title_image']['display']['default']['settings']['styles']['style_2'] = 'ding_primary_small'; /* WAS: 'ding_panorama_primary_small' */
  }

  // Make lead and body on ding_page not required.
  if (isset($data['node-ding_page-field_ding_page_body'])) {
    $data['node-ding_page-field_ding_page_body']['required'] = 0; /* WAS: 1 */
  }
  if (isset($data['node-ding_page-field_ding_page_lead'])) {
    $data['node-ding_page-field_ding_page_lead']['required'] = 0; /* WAS: 1 */
  }

  
  if (isset($data['node-ding_search_context_link-field_search_context_list_image'])) {

    // Make list image on ding_search_context_link not required
    $data['node-ding_search_context_link-field_search_context_list_image']['required'] = 0; /* WAS: 1 */

    // Move fields on ding_search_context_link edit form
    $data['node-ding_search_context_link-field_search_context_list_image']['widget']['weight'] = 4; /* WAS: 32 */
  }

  // Change the default number og covers shown on new_materials page
  if (isset($data['node-new_materials-field_ting_new_materials_items'])) {
    $data['node-new_materials-field_ting_new_materials_items']['default_value'][0]['value'] = 20; /* WAS: 10 */
  }

  // Change the widget for field_ting_new_materials_search
  if (isset($data['node-new_materials-field_ting_new_materials_search'])) {
    $data['node-new_materials-field_ting_new_materials_search']['widget']['settings']['rows'] = 5; /* WAS: '' */
    $data['node-new_materials-field_ting_new_materials_search']['widget']['type'] = 'text_textarea'; /* WAS: 'text_textfield' */
  }


  // Change event category widgit from select box to chack boxes
  if (isset($data['node-ding_event-field_ding_event_category'])) {
   $data['node-ding_event-field_ding_event_category']['widget']['type'] = 'options_buttons'; /* WAS: 'options_select' */
 }

}


function bibsdb_features_override_strongarm_alter(&$data) {


  // Make default state unpublished


  // Make news content unpublished as default
  if (isset($data['node_options_ding_news'])) {
    unset($data['node_options_ding_news']->value[0]);
  }

  // Make event content unpublished and promoted as default
  if (isset($data['node_options_ding_event'])) {
    $data['node_options_ding_event']->value[0] = 'promote'; /* WAS: 'status' */
  }

  // Make page content unpublished and promoted as default
  if (isset($data['node_options_ding_page'])) {
    unset($data['node_options_ding_page']->value[0]);
  }

  // Path auto patterns

  // Page pattern
  if (isset($data['pathauto_node_ding_page_pattern'])) {
    $data['pathauto_node_ding_page_pattern']->value = 'indhold/[node:title]'; /* WAS: '[node:menu-link:parent:url:relative]/[node:menu-link:title]' */
  }

  // Webform pattern
  if (isset($data['pathauto_node_webform_pattern'])) {
    $data['pathauto_node_webform_pattern']->value = '[node:title]'; 
  }

  // New materials pattern
  if (isset($data['pathauto_node_new_materials_pattern'])) {
    $data['pathauto_node_new_materials_pattern']->value = 'nye-udgivelser/[node:title]'; 
  }

  // Event pattern
  if (isset($data['pathauto_node_ding_event_pattern'])) {
    $data['pathauto_node_ding_event_pattern']->value = 'arrangementer/[node:field-ding-event-category:1]/[node:title]'; 
  }



  // Inactivity limit has been lowered from 15 min to 10 min.
  if (isset($data['autologout_role_8_timeout'])) {
    $data['autologout_role_8_timeout']->value = 600; /* WAS: 900 */
  }
  // ...and that must be reflected in message.
  if (isset($data['autologout_inactivity_message'])) {
    $data['autologout_inactivity_message']->value = 'Af sikkerhedsmæssige årsager er du blevet logget ud, da du har været inaktiv de seneste 10 minutter
    
    '; /* WAS: 'Af sikkerhedsmæssige årsager er du blevet logget ud, da du har været inaktiv de seneste 15 minutter
    
    ' */
  }

  // Change Library User Role ind Ding Varnish from authenticated user to guest blogger to prevet caching of content after login.
  // This is to solve the problem that you can't search right after login.
  if (isset($data['ding_varnish_role'])) {
    $data['ding_varnish_role']->value = 5; /* WAS: 2 */
  }
}

/**
 * Theme setting on contact form -  set to bibsdb.
 * Implements hook_default_fe_block_settings_alter().
 * 
 */
function bibsdb_features_override_default_fe_block_settings_alter(&$data) {
  if (isset($data['formblock-contact_site'])) {
    $data['formblock-contact_site']['themes']['bibsdb'] = array(
      'region' => '',
      'status' => 0,
      'theme' => 'bibsdb',
      'weight' => 0,
      ); /* WAS: '' */
  }
}

/**
 * Footer menu headers overridden
 * Implements hook_menu_default_menu_custom_alter().
 */
function bibsdb_features_override_menu_default_menu_custom_alter(&$data) {
  if (isset($data['menu-footer-menu-1'])) {
    $data['menu-footer-menu-1']['title'] = 'Inspiration'; /* WAS: 'Footer menu 1' */
  }
  if (isset($data['menu-footer-menu-2'])) {
    $data['menu-footer-menu-2']['title'] = 'Tilbud'; /* WAS: 'Footer menu 2' */
  }
  if (isset($data['menu-footer-menu-3'])) {
    $data['menu-footer-menu-3']['title'] = 'Sådan gør du'; /* WAS: 'Footer menu 3' */
  }
  if (isset($data['menu-footer-menu-4'])) {
    $data['menu-footer-menu-4']['title'] = 'Information'; /* WAS: 'Footer menu 4' */
  }
}


/**
 * Nodes made not searchable.
 * Sort order of news list in groups changed to publication date from created date.
 * Implements hook_views_default_views_alter().
 */
function bibsdb_features_override_views_default_views_alter(&$data) {
  if (isset($data['ding_node_search'])) {
    $data['ding_node_search']->display['default']->display_options['filters']['type']['value']['ding_search_context_link'] = 'ding_search_context_link'; /* WAS: '' */
    $data['ding_node_search']->display['default']->display_options['filters']['type']['value']['read_circuit_set'] = 'read_circuit_set'; /* WAS: '' */
  }

  if (isset($data['ding_news'])) {

    // Change sort order of all news views
    $data['ding_news']->display['default']->display_options['sorts']['published_at'] = array(
      'id' => 'published_at',
      'table' => 'publication_date',
      'field' => 'published_at',
      'order' => 'DESC',
      );
    unset($data['ding_news']->display['default']->display_options['sorts']['created']);

    // Display the published date instead of the created date in news lists on groups
    $data['ding_news']->display['ding_news_groups_list']->display_options['fields']['created'] = array(
      'id' => 'published_at',
      'table' => 'publication_date',
      'field' => 'published_at',
      'ui_name' => 'Date',
      'label' => '',
      'element_type' => 'span',
      'element_class' => 'news-date',
      'element_label_colon' => FALSE,
      'element_default_classes' => FALSE,
      'date_format' => 'ding_long_date_only',
      'second_date_format' => 'ding_date_only',
      );

    // Change sort order of news on frontpage
    $data['ding_news']->display['ding_news_frontpage_list']->display_options['sorts']['published_at'] = array(
      'id' => 'published_at',
      'table' => 'publication_date',
      'field' => 'published_at',
      'order' => 'DESC',
      );
    unset($data['ding_news']->display['ding_news_frontpage_list']->display_options['sorts']['created']);

    // Display the published date instead of the created date on frontpage
    $data['ding_news']->display['ding_news_frontpage_list']->display_options['fields']['created'] = array(
      'id' => 'published_at',
      'table' => 'publication_date',
      'field' => 'published_at',
      'ui_name' => 'Date',
      'label' => '',
      'element_type' => 'span',
      'element_class' => 'news-date',
      'element_label_colon' => FALSE,
      'element_default_classes' => FALSE,
      'date_format' => 'ding_long_date_only',
      'second_date_format' => 'ding_date_only',
      );

    // Display the published date instead of the created date on the main news list
    $data['ding_news']->display['ding_news_list']->display_options['fields']['created'] = array(
      'id' => 'published_at',
      'table' => 'publication_date',
      'field' => 'published_at',
      'ui_name' => 'Date',
      'label' => '',
      'element_type' => 'span',
      'element_class' => 'news-date',
      'element_label_colon' => FALSE,
      'element_wrapper_type' => 0,
      'element_default_classes' => FALSE,
      'date_format' => 'ding_long_date_only',
      'second_date_format' => 'ding_date_only',
      );
    
  }


}


